//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sneg.АСУ_Склад
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Владелец.
    /// </summary>
    // *** Start programmer edit section *** (Владелец CustomAttributes)

    // *** End programmer edit section *** (Владелец CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВладелецE", new string[] {
            "Фамилия as \'Фамилия\' on \'-Владелец склада\'",
            "Имя as \'Имя\' on \'-Владелец склада\'",
            "Отчество as \'Отчество\' on \'-Владелец склада\'",
            "Склад.Название as \'Название\'",
            "Машина.Марка as \'Марка\'"})]
    [View("ВладелецL", new string[] {
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "Склад.Название as \'Название\'",
            "Машина.Марка as \'Марка\'"})]
    public class Владелец : ICSSoft.STORMNET.DataObject
    {
        
        private string fФамилия;
        
        private string fИмя;
        
        private string fОтчество;
        
        private Sneg.АСУ_Склад.Склад fСклад;
        
        private Sneg.АСУ_Склад.Машина fМашина;
        
        // *** Start programmer edit section *** (Владелец CustomMembers)

        // *** End programmer edit section *** (Владелец CustomMembers)

        
        /// <summary>
        /// Фамилия.
        /// </summary>
        // *** Start programmer edit section *** (Владелец.Фамилия CustomAttributes)

        // *** End programmer edit section *** (Владелец.Фамилия CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Фамилия
        {
            get
            {
                // *** Start programmer edit section *** (Владелец.Фамилия Get start)

                // *** End programmer edit section *** (Владелец.Фамилия Get start)
                string result = this.fФамилия;
                // *** Start programmer edit section *** (Владелец.Фамилия Get end)

                // *** End programmer edit section *** (Владелец.Фамилия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Владелец.Фамилия Set start)

                // *** End programmer edit section *** (Владелец.Фамилия Set start)
                this.fФамилия = value;
                // *** Start programmer edit section *** (Владелец.Фамилия Set end)

                // *** End programmer edit section *** (Владелец.Фамилия Set end)
            }
        }
        
        /// <summary>
        /// Имя.
        /// </summary>
        // *** Start programmer edit section *** (Владелец.Имя CustomAttributes)

        // *** End programmer edit section *** (Владелец.Имя CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Имя
        {
            get
            {
                // *** Start programmer edit section *** (Владелец.Имя Get start)

                // *** End programmer edit section *** (Владелец.Имя Get start)
                string result = this.fИмя;
                // *** Start programmer edit section *** (Владелец.Имя Get end)

                // *** End programmer edit section *** (Владелец.Имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Владелец.Имя Set start)

                // *** End programmer edit section *** (Владелец.Имя Set start)
                this.fИмя = value;
                // *** Start programmer edit section *** (Владелец.Имя Set end)

                // *** End programmer edit section *** (Владелец.Имя Set end)
            }
        }
        
        /// <summary>
        /// Отчество.
        /// </summary>
        // *** Start programmer edit section *** (Владелец.Отчество CustomAttributes)

        // *** End programmer edit section *** (Владелец.Отчество CustomAttributes)
        [StrLen(255)]
        public virtual string Отчество
        {
            get
            {
                // *** Start programmer edit section *** (Владелец.Отчество Get start)

                // *** End programmer edit section *** (Владелец.Отчество Get start)
                string result = this.fОтчество;
                // *** Start programmer edit section *** (Владелец.Отчество Get end)

                // *** End programmer edit section *** (Владелец.Отчество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Владелец.Отчество Set start)

                // *** End programmer edit section *** (Владелец.Отчество Set start)
                this.fОтчество = value;
                // *** Start programmer edit section *** (Владелец.Отчество Set end)

                // *** End programmer edit section *** (Владелец.Отчество Set end)
            }
        }
        
        /// <summary>
        /// Владелец.
        /// </summary>
        // *** Start programmer edit section *** (Владелец.Склад CustomAttributes)

        // *** End programmer edit section *** (Владелец.Склад CustomAttributes)
        [PropertyStorage(new string[] {
                "Склад"})]
        [NotNull()]
        public virtual Sneg.АСУ_Склад.Склад Склад
        {
            get
            {
                // *** Start programmer edit section *** (Владелец.Склад Get start)

                // *** End programmer edit section *** (Владелец.Склад Get start)
                Sneg.АСУ_Склад.Склад result = this.fСклад;
                // *** Start programmer edit section *** (Владелец.Склад Get end)

                // *** End programmer edit section *** (Владелец.Склад Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Владелец.Склад Set start)

                // *** End programmer edit section *** (Владелец.Склад Set start)
                this.fСклад = value;
                // *** Start programmer edit section *** (Владелец.Склад Set end)

                // *** End programmer edit section *** (Владелец.Склад Set end)
            }
        }
        
        /// <summary>
        /// Владелец.
        /// </summary>
        // *** Start programmer edit section *** (Владелец.Машина CustomAttributes)

        // *** End programmer edit section *** (Владелец.Машина CustomAttributes)
        [PropertyStorage(new string[] {
                "Машина"})]
        [NotNull()]
        public virtual Sneg.АСУ_Склад.Машина Машина
        {
            get
            {
                // *** Start programmer edit section *** (Владелец.Машина Get start)

                // *** End programmer edit section *** (Владелец.Машина Get start)
                Sneg.АСУ_Склад.Машина result = this.fМашина;
                // *** Start programmer edit section *** (Владелец.Машина Get end)

                // *** End programmer edit section *** (Владелец.Машина Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Владелец.Машина Set start)

                // *** End programmer edit section *** (Владелец.Машина Set start)
                this.fМашина = value;
                // *** Start programmer edit section *** (Владелец.Машина Set end)

                // *** End programmer edit section *** (Владелец.Машина Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВладелецE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВладелецE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВладелецE", typeof(Sneg.АСУ_Склад.Владелец));
                }
            }
            
            /// <summary>
            /// "ВладелецL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВладелецL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВладелецL", typeof(Sneg.АСУ_Склад.Владелец));
                }
            }
        }
    }
}
