//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sneg.АСУ_Склад
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Поступления.
    /// </summary>
    // *** Start programmer edit section *** (Поступления CustomAttributes)

    // *** End programmer edit section *** (Поступления CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПоступленияE", new string[] {
            "Количество as \'Количество\'"})]
    [View("ПоступленияL", new string[] {
            "Количество as \'Количество\'"})]
    public class Поступления : ICSSoft.STORMNET.DataObject
    {
        
        private decimal fКоличество;
        
        // *** Start programmer edit section *** (Поступления CustomMembers)

        // *** End programmer edit section *** (Поступления CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (Поступления.Количество CustomAttributes)

        // *** End programmer edit section *** (Поступления.Количество CustomAttributes)
        public virtual decimal Количество
        {
            get
            {
                // *** Start programmer edit section *** (Поступления.Количество Get start)

                // *** End programmer edit section *** (Поступления.Количество Get start)
                decimal result = this.fКоличество;
                // *** Start programmer edit section *** (Поступления.Количество Get end)

                // *** End programmer edit section *** (Поступления.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Поступления.Количество Set start)

                // *** End programmer edit section *** (Поступления.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (Поступления.Количество Set end)

                // *** End programmer edit section *** (Поступления.Количество Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПоступленияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПоступленияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПоступленияE", typeof(Sneg.АСУ_Склад.Поступления));
                }
            }
            
            /// <summary>
            /// "ПоступленияL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПоступленияL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПоступленияL", typeof(Sneg.АСУ_Склад.Поступления));
                }
            }
        }
    }
}
