//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sneg.АСУ_Склад
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Склад.
    /// </summary>
    // *** Start programmer edit section *** (Склад CustomAttributes)

    // *** End programmer edit section *** (Склад CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СкладE", new string[] {
            "Название as \'Название\'",
            "Вместимость as \'Вместимость (в тоннах)\'",
            "Поступления.Количество as \'Количество\'"})]
    [AssociatedDetailViewAttribute("СкладE", "ТоварНаСкладе", "ТоварНаСкладеE", true, "", "Товар на складе", true, new string[] {
            ""})]
    [View("СкладL", new string[] {
            "Название as \'Название\'",
            "Вместимость as \'Вместимость\'",
            "Поступления.Количество as \'Количество\'"})]
    public class Склад : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        private decimal fВместимость;
        
        private Sneg.АСУ_Склад.Поступления fПоступления;
        
        private Sneg.АСУ_Склад.DetailArrayOfТоварНаСкладе fТоварНаСкладе;
        
        // *** Start programmer edit section *** (Склад CustomMembers)

        // *** End programmer edit section *** (Склад CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Склад.Название CustomAttributes)

        // *** End programmer edit section *** (Склад.Название CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Склад.Название Get start)

                // *** End programmer edit section *** (Склад.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Склад.Название Get end)

                // *** End programmer edit section *** (Склад.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Склад.Название Set start)

                // *** End programmer edit section *** (Склад.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Склад.Название Set end)

                // *** End programmer edit section *** (Склад.Название Set end)
            }
        }
        
        /// <summary>
        /// Вместимость.
        /// </summary>
        // *** Start programmer edit section *** (Склад.Вместимость CustomAttributes)

        // *** End programmer edit section *** (Склад.Вместимость CustomAttributes)
        public virtual decimal Вместимость
        {
            get
            {
                // *** Start programmer edit section *** (Склад.Вместимость Get start)

                // *** End programmer edit section *** (Склад.Вместимость Get start)
                decimal result = this.fВместимость;
                // *** Start programmer edit section *** (Склад.Вместимость Get end)

                // *** End programmer edit section *** (Склад.Вместимость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Склад.Вместимость Set start)

                // *** End programmer edit section *** (Склад.Вместимость Set start)
                this.fВместимость = value;
                // *** Start programmer edit section *** (Склад.Вместимость Set end)

                // *** End programmer edit section *** (Склад.Вместимость Set end)
            }
        }
        
        /// <summary>
        /// Склад.
        /// </summary>
        // *** Start programmer edit section *** (Склад.Поступления CustomAttributes)

        // *** End programmer edit section *** (Склад.Поступления CustomAttributes)
        [PropertyStorage(new string[] {
                "Поступления"})]
        [NotNull()]
        public virtual Sneg.АСУ_Склад.Поступления Поступления
        {
            get
            {
                // *** Start programmer edit section *** (Склад.Поступления Get start)

                // *** End programmer edit section *** (Склад.Поступления Get start)
                Sneg.АСУ_Склад.Поступления result = this.fПоступления;
                // *** Start programmer edit section *** (Склад.Поступления Get end)

                // *** End programmer edit section *** (Склад.Поступления Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Склад.Поступления Set start)

                // *** End programmer edit section *** (Склад.Поступления Set start)
                this.fПоступления = value;
                // *** Start programmer edit section *** (Склад.Поступления Set end)

                // *** End programmer edit section *** (Склад.Поступления Set end)
            }
        }
        
        /// <summary>
        /// Склад.
        /// </summary>
        // *** Start programmer edit section *** (Склад.ТоварНаСкладе CustomAttributes)

        // *** End programmer edit section *** (Склад.ТоварНаСкладе CustomAttributes)
        public virtual Sneg.АСУ_Склад.DetailArrayOfТоварНаСкладе ТоварНаСкладе
        {
            get
            {
                // *** Start programmer edit section *** (Склад.ТоварНаСкладе Get start)

                // *** End programmer edit section *** (Склад.ТоварНаСкладе Get start)
                if ((this.fТоварНаСкладе == null))
                {
                    this.fТоварНаСкладе = new Sneg.АСУ_Склад.DetailArrayOfТоварНаСкладе(this);
                }
                Sneg.АСУ_Склад.DetailArrayOfТоварНаСкладе result = this.fТоварНаСкладе;
                // *** Start programmer edit section *** (Склад.ТоварНаСкладе Get end)

                // *** End programmer edit section *** (Склад.ТоварНаСкладе Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Склад.ТоварНаСкладе Set start)

                // *** End programmer edit section *** (Склад.ТоварНаСкладе Set start)
                this.fТоварНаСкладе = value;
                // *** Start programmer edit section *** (Склад.ТоварНаСкладе Set end)

                // *** End programmer edit section *** (Склад.ТоварНаСкладе Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СкладE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СкладE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СкладE", typeof(Sneg.АСУ_Склад.Склад));
                }
            }
            
            /// <summary>
            /// "СкладL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СкладL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СкладL", typeof(Sneg.АСУ_Склад.Склад));
                }
            }
        }
    }
}
